"""
CDK CLI Generator
=================
Generates template code for new OpenStockAPI providers.
"""

import os
import argparse
import sys

STOCK_PROVIDER_TEMPLATE = """\"\"\"
{name_cap} Provider — {market} Stock Market Data
===================================================
Generated by OpenStock CDK on {date}

Standard: BaseStockProvider
Market: {market}
Asset Class: stock
\"\"\"

from datetime import datetime
from typing import List, Optional, Any

from openstockapi.cdk import BaseStockProvider
from openstockapi.core.types import DataTier
from openstockapi.core.models import OHLCVBar, FinancialItem, CompanyProfile
from openstockapi.core.http_client import http_client
from openstockapi.core.exceptions import DataParseError
from openstockapi.core.utils import parse_date


class {name_cap}Provider(BaseStockProvider):
    \"\"\"
    Data provider for {name_cap} ({market} Stock).
    \"\"\"

    name: str = "{name_lower}"
    market: str = "{market}"
    required_tier: DataTier = DataTier.FREE
    supported_methods: List[str] = [
        "get_ohlcv",
    ]

    def _get_headers(self) -> dict:
        return {{
            "User-Agent": "Mozilla/5.0",
        }}

    def get_ohlcv(self, symbol: str, resolution: str, from_date: str, to_date: str) -> List[OHLCVBar]:
        \"\"\"
        Fetch OHLCV historical price data.
        \"\"\"
        f_dt = parse_date(from_date) if from_date else None
        t_dt = parse_date(to_date) if to_date else None
        
        # TODO: Implement the actual API request
        url = f"https://api.example.com/{{symbol}}/ohlcv"
        
        try:
            # res = http_client.request("GET", url, headers=self._get_headers())
            # data = res.json()
            results = []
            # TODO: parse response and append OHLCVBar objects
            return results
        except Exception as e:
            raise DataParseError(f"{name_cap}Provider failed to fetch OHLCV: {{e}}")

    def get_financial_statements(self, symbol: str, stmt_type: str, period: str) -> List[FinancialItem]:
        \"\"\"
        Fetch financial statements.
        \"\"\"
        # TODO: Implement financial statements fetch
        return []
"""

CRYPTO_PROVIDER_TEMPLATE = """\"\"\"
{name_cap} Provider — Crypto Market Data
===================================================
Generated by OpenStock CDK on {date}

Standard: BaseCryptoProvider
Market: GLOBAL
Asset Class: crypto
\"\"\"

from datetime import datetime
from typing import List, Optional, Any

from openstockapi.cdk import BaseCryptoProvider
from openstockapi.core.types import DataTier
from openstockapi.core.models import OHLCVBar, CryptoProfile
from openstockapi.core.exceptions import DataParseError
from openstockapi.core.utils import parse_date


class {name_cap}Provider(BaseCryptoProvider):
    \"\"\"
    Data provider for {name_cap} (Crypto).
    \"\"\"

    name: str = "{name_lower}"
    market: str = "GLOBAL"
    required_tier: DataTier = DataTier.FREE
    supported_methods: List[str] = [
        "get_crypto_ohlcv",
        "get_crypto_profile",
    ]

    def get_crypto_ohlcv(self, symbol: str, resolution: str, from_date: str, to_date: str) -> List[OHLCVBar]:
        f_dt = parse_date(from_date) if from_date else None
        t_dt = parse_date(to_date) if to_date else None
        # TODO: Implement crypto OHLCV fetch
        return []

    def get_crypto_profile(self, symbol: str) -> CryptoProfile:
        # TODO: Implement crypto profile fetch
        raise NotImplementedError()
"""

FOREX_PROVIDER_TEMPLATE = """\"\"\"
{name_cap} Provider — Forex Market Data
===================================================
Generated by OpenStock CDK on {date}

Standard: BaseForexProvider
Market: GLOBAL
Asset Class: forex
\"\"\"

from datetime import datetime
from typing import List, Optional, Any

from openstockapi.cdk import BaseForexProvider
from openstockapi.core.types import DataTier
from openstockapi.core.models import OHLCVBar, ForexProfile
from openstockapi.core.exceptions import DataParseError
from openstockapi.core.utils import parse_date


class {name_cap}Provider(BaseForexProvider):
    \"\"\"
    Data provider for {name_cap} (Forex).
    \"\"\"

    name: str = "{name_lower}"
    market: str = "GLOBAL"
    required_tier: DataTier = DataTier.FREE
    supported_methods: List[str] = [
        "get_forex_ohlcv",
        "get_forex_rates",
    ]

    def get_forex_ohlcv(self, symbol: str, resolution: str, from_date: str, to_date: str) -> List[OHLCVBar]:
        f_dt = parse_date(from_date) if from_date else None
        t_dt = parse_date(to_date) if to_date else None
        # TODO: Implement forex OHLCV fetch
        return []

    def get_forex_rates(self, base: str, quote: str) -> Any:
        # TODO: Implement forex rates fetch
        raise NotImplementedError()
"""

TEST_UNIT_TEMPLATE = """\"\"\"
Unit tests for {name_cap}Provider
\"\"\"

import pytest
from unittest.mock import patch, MagicMock
from openstockapi.providers.vn_stock.providers.{name_lower} import {name_cap}Provider
from openstockapi.license.session import Session, set_current_session

@pytest.fixture(autouse=True)
def setup_free_session():
    set_current_session(Session("free"))

def test_{name_lower}_ohlcv_basic():
    provider = {name_cap}Provider()
    assert provider.name == "{name_lower}"
"""

TEST_CDK_TEMPLATE = """\"\"\"
CDK Contract tests for {name_cap}Provider
\"\"\"

from openstockapi.providers.vn_stock.providers.{name_lower} import {name_cap}Provider
from .base_test import BaseCDKProviderTest

class Test{name_cap}ProviderCDK(BaseCDKProviderTest):
    PROVIDER_CLASS = {name_cap}Provider
    SAMPLE_SYMBOL = "HPG"
    SAMPLE_MARKET = "{market}"
"""


def generate(name: str, market: str, asset_type: str):
    name_lower = name.lower()
    name_cap = name.capitalize()
    market_lower = market.lower()
    market_upper = market.upper()
    type_lower = asset_type.lower()
    type_cap = "Stock" if type_lower == "stock" else ("Crypto" if type_lower == "crypto" else "Forex")

    import datetime
    today_str = datetime.date.today().strftime("%Y-%m-%d")

    # Define target paths
    root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
    
    # 1. Create Provider
    provider_dir = os.path.join(root_dir, "openstockapi", "providers", f"{market_lower}_stock" if type_lower == "stock" else type_lower, "providers")
    if not os.path.exists(provider_dir):
        # Fallback to general vn_stock for now if folder hierarchy doesn't exist
        provider_dir = os.path.join(root_dir, "openstockapi", "providers", "vn_stock", "providers")
    
    os.makedirs(provider_dir, exist_ok=True)
    provider_file = os.path.join(provider_dir, f"{name_lower}.py")
    
    if type_lower == "stock":
        template = STOCK_PROVIDER_TEMPLATE
    elif type_lower == "crypto":
        template = CRYPTO_PROVIDER_TEMPLATE
    else:
        template = FOREX_PROVIDER_TEMPLATE

    with open(provider_file, "w", encoding="utf-8") as f:
        f.write(template.format(
            name_lower=name_lower, name_cap=name_cap, market=market_upper,
            type_lower=type_lower, type_cap=type_cap, date=today_str
        ))
    print(f"  [+] Created provider: {os.path.relpath(provider_file, root_dir)}")

    # 2. Create Unit Test
    test_unit_dir = os.path.join(root_dir, "tests", "unit")
    os.makedirs(test_unit_dir, exist_ok=True)
    test_unit_file = os.path.join(test_unit_dir, f"test_{name_lower}.py")
    with open(test_unit_file, "w", encoding="utf-8") as f:
        f.write(TEST_UNIT_TEMPLATE.format(name_lower=name_lower, name_cap=name_cap))
    print(f"  [+] Created unit test: {os.path.relpath(test_unit_file, root_dir)}")

    # 3. Create CDK Test
    test_cdk_dir = os.path.join(root_dir, "tests", "cdk")
    os.makedirs(test_cdk_dir, exist_ok=True)
    test_cdk_file = os.path.join(test_cdk_dir, f"test_{name_lower}_cdk.py")
    with open(test_cdk_file, "w", encoding="utf-8") as f:
        f.write(TEST_CDK_TEMPLATE.format(name_lower=name_lower, name_cap=name_cap, market=market_upper))
    print(f"  [+] Created CDK contract test: {os.path.relpath(test_cdk_file, root_dir)}")

    print("\nManual steps required:")
    print(f"  1. Register in openstockapi/providers/__init__.py:")
    print(f"     from openstockapi.providers.vn_stock.providers.{name_lower} import {name_cap}Provider")
    print(f"     PROVIDERS[\"{name_lower}\"] = {name_cap}Provider()")
    print(f"  2. Add key \"{name_lower}\" to openstockapi/config/settings.py priority list.")


def main():
    parser = argparse.ArgumentParser(description="OpenStock Connector Development Kit (CDK) Generator")
    parser.add_argument("--name", required=True, help="Name of the provider (e.g. ssi, kbs)")
    parser.add_argument("--market", default="VN", help="Market identifier (e.g. VN, US)")
    parser.add_argument("--type", default="stock", choices=["stock", "crypto", "forex"], help="Asset class type")

    args = parser.parse_args()
    
    print("--- OpenStock CDK - Provider Generator ---")
    print("============================================")
    generate(args.name, args.market, args.type)


if __name__ == "__main__":
    main()
